service: urvsquad-bot

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment:
    USB_TELEGRAM_BOT_TOKEN: ${env:USB_TELEGRAM_BOT_TOKEN}

functions:
  donation-fundraiser-countMessages:
    handler: src/donation-raiser/countMessages.handler
    events:
      - schedule: cron(0 */8 * * ? *)
  donation-fundraiser-postUpdateMessage:
    handler: src/donation-raiser/postUpdateMessage.handler
    events:
      - schedule: cron(0 12 * * ? *)

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
