service: urvsquad-bot

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2
  environment:
    USB_TELEGRAM_BOT_TOKEN: ${env:USB_TELEGRAM_BOT_TOKEN}

functions:
  hello:
    handler: src/donation-raiser/countMessages.handler
    events:
      - schedule: rate(8 hours)

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies
